function(create_resources dir output_c output_h)
    file(WRITE ${output_c} "")
    file(WRITE ${output_h} "")
    file(APPEND ${output_h} "#pragma once\n")
    file(GLOB bins ${dir}/*)
    foreach(bin ${bins})
        string(REGEX MATCH "([^/]+)$" filename ${bin})
        string(REGEX REPLACE "\\.| |-" "_" filename ${filename})
        file(READ ${bin} filedata HEX)
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," filedata ${filedata})
        file(APPEND ${output_c} "const unsigned char ${filename}[] = {${filedata}};\nconst unsigned ${filename}_size = sizeof(${filename});\n")
        file(APPEND ${output_h} "extern const unsigned char ${filename}[];\nextern const unsigned ${filename}_size;\n")
    endforeach()
endfunction()
